Bare minimum to update to woohoolabs/yin:^4.0
qpautrat/woohoolabs-yin-bundle pull request #16
Opened 2019-07-16 13:05 UTC by Doqnach

PR with the bare minimum of work to update to woohoolabs/yin:^4.0 plus latest versions of dependencies.

I'm not familiar enough with `qpautrat/woohoolabs-yin-bundle` to judge right now if more work is needed at other places in the code, nor familiar enough with Symfony bundles to make any adjustments for Symfony 4.

Any way to enable auto-wiring of `MyController::myRoute(JsonApi $jsonApi)`?

2019-07-16 15:02 UTC, qpautrat requested changes
Hello @Doqnach 👋 

Thank you for your work!
It looks good to me. 👏 
Can you just remove phpspec upgrade please ?

2019-07-16 15:02 UTC, qpautrat commented on composer.json
> +        "zendframework/zend-diactoros": "^2.1",
We do not need this dependency anymore. See #17 .

2019-07-16 15:02 UTC, qpautrat commented on composer.json
> +        "phpspec/phpspec": "^5.1"
I prefer not to bump to a major version even if it is a dev requirement.

2019-07-16 15:02 UTC, qpautrat commented on src/Request/Request.php
> +class Request extends JsonApiRequest
We really should consider to think about moving back to original class but it is another story :)

2019-07-16 15:02 UTC, qpautrat commented on src/Request/Request.php
> -        $content = $this->serverRequest->getBody()->getContents();
Related to my previous comment, I did back then (#4) this class to rewrite this line. They used `__toString()` method instead of `getContents()`. It was a long time ago. It seems it is not the case anymore but to be sure I suggest to bump to a major version to avoid any unwanted breaking backward compatibility.

2019-07-16 15:05 UTC, Doqnach commented on src/Request/Request.php
> +class Request extends JsonApiRequest
I was thinking the same, but your implementation has a few helper methods that the base class doesn't have. So I figured to keep it.

2019-07-16 15:06 UTC, Doqnach commented on src/Request/Request.php
> -        $content = $this->serverRequest->getBody()->getContents();
Since this is also a jump in major version for `woohoolabs/yin`, that would not be a bad idea.

2019-07-16 15:08 UTC, Doqnach commented on composer.json
> +        "phpspec/phpspec": "^5.1"
Reverted this change.

2019-07-16 15:11 UTC, Doqnach commented on composer.json
> +        "zendframework/zend-diactoros": "^2.1",
Yeah I noticed the commit so I had merged it already ;-].

2019-07-16 15:53 UTC, qpautrat commented on src/Request/Request.php
> -        $content = $this->serverRequest->getBody()->getContents();
It is my job ;)

2019-07-16 15:57 UTC, qpautrat commented
Concerning your question 
>Any way to enable auto-wiring of MyController::myRoute(JsonApi $jsonApi)?

If you follow the doc it should be ok. You can edit your services definition like this:

```yaml
services:
        _defaults:
            ...
            bind:
                $jsonApi: '@qp_woohoolabs_yin.json_api'
```

Is it what you asked for ?

2019-07-16 15:57 UTC, qpautrat approved these changes

2019-07-16 15:58 UTC, merged

2019-07-17 07:44 UTC, moafred commented
Or like this :)

```yaml
services:
    _defaults:
       ...
        bind:
            WoohooLabs\Yin\JsonApi\JsonApi: '@qp_woohoolabs_yin.json_api'
```

2019-07-17 07:44 UTC, moafred commented
Thanks @Doqnach !

2019-07-17 08:27 UTC, Doqnach commented
> Or like this :)
> 
> 
> ```yaml
> services:
>     _defaults:
>        ...
>         bind:
>             WoohooLabs\Yin\JsonApi\JsonApi: '@qp_woohoolabs_yin.json_api'
> ```

I think this notation is better than the one in the current docs. Was mostly wondering if such a thing could be automatically done when requiring the composer package, or if you always have to add this by hand.

Though this is maybe not the place to have this discussion, but perhaps an idea to move the docs from `src/Resources/doc/index.rst` to the `README.md`, and update it with @moafred's suggestion?

2019-07-17 08:46 UTC, moafred commented
> could be automatically done when requiring the composer package,

Symfony recipes add the ability to add new files after required & installed a package but does not offer the possibility to edit files. The `_defaults` part cannot be redefined elsewhere.

> Though this is maybe not the place to have this discussion, but perhaps an idea to move the docs from src/Resources/doc/index.rst to the README.md, and update it with @moafred's suggestion?

Good idea ! @qpautrat ?

2019-07-17 08:53 UTC, Doqnach commented
See #18